---
- name: Chapter 5 final task
  hosts: servers
  become: true
  gather_facts: true
#  remote_user: devops

  tasks:
  - name: Using the ansible.builtin.template module, replace /etc/motd using the motd.j2 file
    ansible.builtin.template:
      src: template/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: '0644'

  - name: verify file exists
    register: stat
    ansible.builtin.stat:
      path: /etc/motd

  - name: print out result of stat
    ansible.builtin.debug:
      var: stat
  
  - name: Copy files/issue into /etc/ dir preserving ownership/permissions
    ansible.builtin.copy:
      src: files/issue
      dest: /etc/
      owner: root
      group: root
      mode: '0644'

  - name: Ensure /etc/issue.net is a symbolic link to /etc/issue. Revert if needed
    ansible.builtin.file:
      src: /etc/issue
      dest: /etc/issue.net
      owner: root
      group: root
      mode: '0644'      