- name: Chapter 2 lab exercise
  hosts: serverb.lab.example.com
  become: true

  tasks:
    - name: install latest versions of firewalld, httpd, mariadb-server, php, and php-mysqlnd.
      ansible.builtin.dnf:
        name:
          - firewalld
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
        state: latest

    - name: Ensure firewalld is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Ensure firewalld allows http service to run
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Ensure httpd service is enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Ensure mariadb service is enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy index.php to /var/www/html/ with 0644 permissions
      ansible.builtin.copy:
        src: index.php
        dest: /var/www/html/index.php
        mode: '0644'


- name: Ensure the control node can access the webserver
  hosts: workstation
  become: false

  tasks:
    - name: check the webpage
      ansible.builtin.uri:
        url: http://serverb.lab.example.com
        status_code: 200
