---
- name: Guided exercise 5.2 - step 2 (fetch log files)
  hosts: all
  become: true
  gather_facts: true
  remote_user: root

  tasks:
    - name: Using fetch to grab files
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: secure-backups/
        flat: false
