---
- name: Step 3 - Create the copy-file.yml file
  hosts: all
  remote_user: root

  tasks:
    - name: Copy file to all hosts
      ansible.builtin.copy:
        src: /home/student/file-manage/files/users.txt
        dest: /home/devops/users.txt
        owner: devops
        group: devops
        mode: u+rw,g-wx,o-rwx
        setype: samba_share_t
